project:
  type: website

website: 
  title: "IS415-GA"
  navbar: 
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Chapter 1: Geospatial Data Science with R"
            href: "Hands-on_Exercise/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Chapter 2: Thematic Mapping and GeoVisualisation with R"
            href: "Hands-on_Exercise/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Chapter 4: 1st Order Spatial Point Patterns Analysis Methods"
            href: "Hands-on_Exercise/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "Chapter 5: 2nd Order Spatial Point Patterns Analysis Methods"
            href: "Hands-on_Exercise/Hands-on_Ex03/Hands-on_Ex03b.html"
          - text: "Chapter 7: Network Constrained Spatial Point Patterns Analysis"
            href: "Hands-on_Exercise/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Chapter 8: Spatial Weights and Applications"
            href: "Hands-on_Exercise/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Chapter 9: Global Measures of Spatial Autocorrelation"
            href: "Hands-on_Exercise/Hands-on_Ex05/Hands-on_Ex05a.html"
          - text: "Chapter 10: Local Measures of Spatial Autocorrelation"
            href: "Hands-on_Exercise/Hands-on_Ex05/Hands-on_Ex05b.html"
          #- text: "Geographically Weighted PCA"
            #href: "Hands-on_Exercise/Hands-on_Ex11/Hands-on_Ex11.html"
          - text: "Chapter 12: Geographical Segmentation with Spatially Constrained Clustering Techniques"
            href: "Hands-on_Exercise/Hands-on_Ex12/Hands-on_Ex12.html"
          #- text: "Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method"
            #href: "Hands-on_Exercise/Hands-on_Ex13/Hands-on_Ex13.html"
          - text: "Chapter 14: Geographically Weighted Predictive Models"
            href: "Hands-on_Exercise/Hands-on_Ex09/Hands-on_Ex09.html"
          #- text: "Processing and Visualising Flow Data"
            #href: "Hands-on_Exercise/Hands-on_Ex15/Hands-on_Ex15.html"
          #- text: "Calibrating Spatial Interaction Models with R"
            #href: "Hands-on_Exercise/Hands-on_Ex16/Hands-on_Ex16.html"
          - text: "Chapter 17: Modelling Geographical Accessibility"
            href: "Hands-on_Exercise/Hands-on_Ex10/Hands-on_Ex10.html"

      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-Class_Exercise/InClassEx01/InClassEx01.html"
          - text: "In-class Exercise 2"
            href: "In-Class_Exercise/InClassEx02/InClassEx02.html"
          - text: "In-class Exercise 3"
            href: "In-Class_Exercise/InClassEx03/InClassEx03.html"
          - text: "In-class Exercise 4"
            href: "In-Class_Exercise/InClassEx04/InClassEx04.html"
          - text: "In-class Exercise 5"
            href: "In-Class_Exercise/InClassEx05/InClassEx05.html"
          - text: "In-class Exercise 6"
            href: "In-Class_Exercise/InClassEx06/InClassEx06.html"
          - text: "In-class Exercise 7"
            href: "In-Class_Exercise/InClassEx07/InClassEx07.html"
          - text: "In-class Exercise 8"
            href: "In-Class_Exercise/InClassEx08/InClassEx08.html"
          - text: "In-class Exercise 9"
            href: "In-Class_Exercise/InClassEx09/InClassEx09.html"
          - text: "In-class Exercise 10"
            href: "In-Class_Exercise/InClassEx10/InClassEx10.html"
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual
