project:
  type: website

website: 
  title: "IS415-GA"
  navbar: 
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "HandsOnExercise/HandsOnEx01/HandsOnEx01.html"
          - text: "Hands-on Exercise 2"
            href: "HandsOnExercise/HandsOnEx02/HandsOnEx02.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-Class_Exercise/InClassEx01/InClassEx01.html"
          - text: "In-class Exercise 2"
            href: "In-Class_Exercise/InClassEx02/InClassEx02.html"
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual
