project:
  type: website
  render: 
    - "Hands-on-Exercise/Hands-on_Ex01/Hands-on_Ex01.qmd"  

website: 
  title: "IS415-GA"
  navbar: 
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Exercise/Hands-on_Ex01/Hands-on_Ex01.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
