project:
  type: website

website: 
  title: "IS415-GA"
  navbar: 
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1: Geospatial Data Science with R"
            href: "Hands-on_Exercise/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2: Thematic Mapping and GeoVisualisation with R"
            href: "Hands-on_Exercise/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3: 1st & 2nd Order Spatial Point Patterns Analysis Methods"
            href: "Hands-on_Exercise/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4: Network Constrained Spatial Point Patterns Analysis"
            href: "In-Class_Exercise/InClassEx04/InClassEx04.html"
          - text: "Hands-on Exercise 5: Spatial Weights and Applications"
            href: "Hands-on_Exercise/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6: Global & Local Measures of Spatial Autocorrelation"
            href: "Hands-on_Exercise/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 7: Shiny App"
            href: "https://jezeleii.shinyapps.io/GAShiny/"
          - text: "Hands-on Exercise 8: Geographical Segmentation with Spatially Constrained Clustering Techniques"
            href: "Hands-on_Exercise/Hands-on_Ex08/Hands-on_Ex08.html"
          - text: "Hands-on Exercise 9: Spatially Constrained Clustering Analysis"
            href: "In-Class_Exercise/InClassEx09/InClassEx09.html"
          - text: "Hands-on Exercise 10: Regression Modelling of Geographically Referenced Data"
            href: "Hands-on_Exercise/Hands-on_Ex10/Hands-on_Ex10.html"
          - text: "Hands-on Exercise 11: Geographically Weighted Regression" 
            href: "Hands-on_Exercise/Hands-on_Ex11/Hands-on_Ex11.html"
          - text: "Hands-on Exercise 12: Geographically Weighted Predictive Modelling" 
            href: "Hands-on_Exercise/Hands-on_Ex12/Hands-on_Ex12.html"
          

      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-Class_Exercise/InClassEx01/InClassEx01.html"
          - text: "In-class Exercise 2"
            href: "In-Class_Exercise/InClassEx02/InClassEx02.html"
          - text: "In-class Exercise 3"
            href: "In-Class_Exercise/InClassEx03/InClassEx03.html"
          - text: "In-class Exercise 4"
            href: "In-Class_Exercise/InClassEx04/InClassEx04.html"
          - text: "In-class Exercise 5"
            href: "In-Class_Exercise/InClassEx05/InClassEx05.html"
          - text: "In-class Exercise 6"
            href: "In-Class_Exercise/InClassEx06/InClassEx06.html"
          - text: "In-class Exercise 7"
            href: "https://jezeleii.shinyapps.io/GAShiny/"
          - text: "In-class Exercise 8"
            href: "In-Class_Exercise/InClassEx08/InClassEx08.html"
          - text: "In-class Exercise 9"
            href: "In-Class_Exercise/InClassEx09/InClassEx09.html"
          - text: "In-class Exercise 10"
            href: "In-Class_Exercise/InClassEx10/InClassEx10.html"
          - text: "In-class Exercise 11"
            href: "In-Class_Exercise/InClassEx11/InClassEx11.html"
          - text: "In-class Exercise 12"
            href: "In-Class_Exercise/InClassEx12/InClassEx12.html"
            
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-Home_Exercise/TakeHomeEx01/TakeHomeEx01.html"
          - text: "Take-home Exercise 2"
            href: "Take-Home_Exercise/TakeHomeEx02/TakeHomeEx02.html"
          - text: "Take-home Exercise 3"
            href: "Take-Home_Exercise/TakeHomeEx03/TakeHomeEx03.html"
        
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual
