project:
  type: website

website: 
  title: "IS415-GA"
  navbar: 
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Exercise/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
            href: "In-Class_Exercise/InClassEx01/InClassEx01.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual
