---
title: "test"
---

```{r}
pacman::p_load(sf, raster, spatstat, tmap, tidyverse, dplyr, devtools, sp, tidyr, stringr, rvest, xml2)
```

```{r}
childcare_sf <- st_read("data/child-care-services-geojson.geojson") %>% 
st_transform(crs=3414)
```

```{r}
glimpse(childcare_sf)
```

```{r}
clean_html <- function(html_content) {

  parsed_html <- read_html(html_content)
  rows <- parsed_html %>%
    html_nodes("tr")
  
  headers <- c()
  data <- c()
  

  for (row in rows) {
    row_headers <- row %>% html_nodes("th") %>% html_text(trim = TRUE)
    row_data <- row %>% html_nodes("td") %>% html_text(trim = TRUE)
    
    if (length(row_headers) > 0) {
      headers <- c(headers, row_headers)
    }
    
    if (length(row_data) > 0) {
      data <- c(data, row_data)
    }
  }
  

  table_df <- data.frame(
    Header = rep(headers, length.out = length(data)),
    Data = data,
    stringsAsFactors = FALSE
  )
  
  table_df$Data <- ifelse(table_df$Data == "", NA, table_df$Data)
  

  cleaned_data <- table_df %>%
    tidyr::pivot_wider(names_from = Header, values_from = Data, values_fill = list(Data = NA))
  
  return(cleaned_data)
}

childcare_sf_clean <- childcare_sf %>% 
  rowwise() %>% 
  mutate(Cleaned_Description = list(clean_html(Description))) %>% 
  unnest(Cleaned_Description) %>% # Correct function name here
  ungroup()

#print(childcare_sf_clean)

#===============
childcare_sf_cleaned <- childcare_sf_clean %>% select(-Attributes) %>%  select(-Description)

# Shift the column names 2 positions up starting from the 3rd column
colnames(childcare_sf_cleaned)[3:(ncol(childcare_sf_cleaned)-3)] <- colnames(childcare_sf_cleaned)[4:ncol(childcare_sf_cleaned)]

# Remove the last 2 columns, which are now empty after shifting
childcare_sf_cleaned <- childcare_sf_cleaned[, 1:(ncol(childcare_sf_cleaned))]

# View the cleaned and shifted data
#print(childcare_sf_cleaned)
```

```{r}
glimpse(childcare_sf_cleaned)
```

```{r}
str(childcare_sf_cleaned)
```

From the structure of the childcare_sf_cleaned(), we can further improve how the data is shown by renaming the first column to KML_ID, and shifting the 'Name' Column to the second column, to accurately reflect the information in the data. In the code above we've removed 'ADDRESSBLOCKHOUSENUMBER' , so we will add it back in its respective position

```{r}

names(childcare_sf_cleaned)[1] <- "kml_id"

childcare_sf_cleaned <- childcare_sf_cleaned[, c(1, 11, 2:10, 12:ncol(childcare_sf_cleaned))]

childcare_sf_cleaned$ADDRESSBLOCKHOUSENUMBER <- NA 

childcare_sf_cleaned <- childcare_sf_cleaned[, c(1:3, ncol(childcare_sf_cleaned), 4:(ncol(childcare_sf_cleaned)-1))]

head(childcare_sf_cleaned)
```
